/**
 * The landing's example exchange, recorded from the real core: the slip, the policy and
 * each step's Lens. The page renders it until the core runs in the browser.
 * Generated by site/scripts/landing-exchange.mjs; don't edit by hand.
 */
import type { ReceiptView, SlipView, UndoneView } from './slip-view';

export interface Recorded {
  params: { items: { sku: string; qty: number }[]; deliver: string };
  policy: { sentence: string; caveats: string[]; grant: string };
  slip: SlipView;
  receipt: ReceiptView;
  undone: UndoneView;
  lens: { proposals: string; consent: string; receipt: string; undo: string };
}

export const RECORDED: Recorded = {
  "params": {
    "items": [
      {
        "sku": "m047",
        "qty": 2
      },
      {
        "sku": "m055",
        "qty": 2
      }
    ],
    "deliver": "2026-09-29"
  },
  "policy": {
    "sentence": "For the next 8 hours, your agent may take low-risk actions at shop.example that spend up to $40 each and $100 in total.",
    "caveats": [
      "{\"svc\":[\"shop.example\"]}",
      "{\"risk\":\"low\"}",
      "{\"each\":{\"of\":\"spend\",\"max\":4000,\"scale\":2,\"unit\":\"USD\"}}",
      "{\"total\":{\"of\":\"spend\",\"max\":10000,\"scale\":2,\"unit\":\"USD\"}}",
      "{\"exp\":1790656417}"
    ],
    "grant": "pg1.W3sicCI6eyJjYXZlYXRzIjpbeyJzdmMiOlsic2hvcC5leGFtcGxlIl19LHsicmlzayI6ImxvdyJ9LHsiZWFjaCI6eyJtYXgiOjQwMDAsIm9mIjoic3BlbmQiLCJzY2FsZSI6MiwidW5pdCI6IlVTRCJ9fSx7InRvdGFsIjp7Im1heCI6MTAwMDAsIm9mIjoic3BlbmQiLCJzY2FsZSI6MiwidW5pdCI6IlVTRCJ9fSx7ImV4cCI6MTc5MDY1NjQxN31dLCJpYXQiOjE3OTA2Mjc2MTcsImlzcyI6ImVkMjU1MTk6ckJOSmN0NmVIdi1MUlVtRTVWOU1iR2FqUTNmZHRZVGNrUi1pSlNnc3FibyIsIm5vbmNlIjoiXzM2UE1rZVM3cnhQdE50cyIsInN1YiI6ImVkMjU1MTk6TjIwZjR4QXBhdENCQWt2cVFaQTcxVG11UWxzUEhQTkpJcGlLVFpWa0xQcyJ9LCJzIjoiTGxOSGtsbDBoNThaY29JbDRpY1Z1SmM2MktYejVQeWxPZEZLeTVBUnhDSEo0eTNnWUMwTzdhSE9ReE8yRFVJb3hMMC0zU1VKbVIxZ2kydExCdm8wQ1EifV0"
  },
  "slip": {
    "id": "p_oVk1jeGo",
    "service": "shop.example",
    "summary": "4 meals for 2026-09-29 — 53.95 USD",
    "effects": [
      "+ create order/o1001 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)",
      "+ create charge — 53.95 USD to card ••4242"
    ],
    "uses": "spend 53.95 USD",
    "risk": "low",
    "undo": "within 2h",
    "hash": "92lQCj9OvSaMXcGQkmojFNVulfs9MhK2QFIhylWhqm8",
    "reason": "spend over the per-commit limit of 40.00 USD; your principal must approve this exact proposal"
  },
  "receipt": {
    "id": "r_gkZrOVyT",
    "undoUntil": "2026-09-28 22:33 UTC",
    "result": [
      "order: o1001",
      "status: placed"
    ]
  },
  "undone": {
    "id": "r_bG4IIzbd",
    "undoes": "r_gkZrOVyT"
  },
  "lens": {
    "proposals": "2 proposals — risk: low · undo: 2h · expires: 2026-09-28T20:44Z:\n[p_oVk1jeGo] 4 meals for 2026-09-29 — 53.95 USD\n  + create order/o1001 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)\n  + create charge — 53.95 USD to card ••4242\n  uses: spend 53.95 USD\n  data:\n    subtotal: 47.96\n    delivery: 5.99\n[p_F2A_ZCBM] 4 meals for 2026-09-29 (express, by noon) — 62.94 USD\n  + create order/o1002 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)\n  + create charge — 62.94 USD to card ••4242\n  uses: spend 62.94 USD\n  data:\n    subtotal: 47.96\n    delivery: 5.99\n    express: 8.99",
    "consent": "✗ consent_required: spend over the per-commit limit of 40.00 USD; your principal must approve this exact proposal\n  consent: principal must approve 92lQCj9OvSaMXcGQkmojFNVulfs9MhK2QFIhylWhqm8 (4 meals for 2026-09-29 — 53.95 USD)",
    "receipt": "✓ 4 meals for 2026-09-29 — 53.95 USD (receipt r_gkZrOVyT) · undo until 2026-09-28T22:33:37Z\n  result:\n    order: o1001\n    status: placed",
    "undo": "↶ undid r_gkZrOVyT: 4 meals for 2026-09-29 — 53.95 USD (receipt r_bG4IIzbd)"
  }
};
