/**
 * The landing's dinner example, recorded from the real core: the slip, the policy and each
 * step's Lens. The page renders it until the core runs in the browser.
 * Generated by site/scripts/landing-exchange.mjs; don't edit by hand.
 */
import type { ReceiptView, SlipView, UndoneView } from './slip-view';

export interface Recorded {
  params: { items: { sku: string; qty: number }[]; deliver: string };
  /** How many proposals the shop made; the slip shows the first. */
  count: number;
  /** What the proposal spends, in dollars. */
  spend: number;
  policy: { sentence: string; caveats: string[]; grant: string };
  slip: SlipView;
  receipt: ReceiptView;
  undone: UndoneView;
  lens: { proposals: string; consent: string; receipt: string; undo: string };
}

export const RECORDED: Recorded = {
  "params": {
    "items": [
      {
        "sku": "m047",
        "qty": 2
      },
      {
        "sku": "m055",
        "qty": 2
      }
    ],
    "deliver": "2026-10-01"
  },
  "count": 2,
  "spend": 53.95,
  "policy": {
    "sentence": "For the next 8 hours, your agent may take low-risk actions at shop.example or calendar.example that spend up to $40 each and $100 in total.",
    "caveats": [
      "{\"svc\":[\"shop.example\",\"calendar.example\"]}",
      "{\"risk\":\"low\"}",
      "{\"each\":{\"of\":\"spend\",\"max\":4000,\"scale\":2,\"unit\":\"USD\"}}",
      "{\"total\":{\"of\":\"spend\",\"max\":10000,\"scale\":2,\"unit\":\"USD\"}}",
      "{\"exp\":1790755691}"
    ],
    "grant": "pg1.W3sicCI6eyJjYXZlYXRzIjpbeyJzdmMiOlsic2hvcC5leGFtcGxlIiwiY2FsZW5kYXIuZXhhbXBsZSJdfSx7InJpc2siOiJsb3cifSx7ImVhY2giOnsibWF4Ijo0MDAwLCJvZiI6InNwZW5kIiwic2NhbGUiOjIsInVuaXQiOiJVU0QifX0seyJ0b3RhbCI6eyJtYXgiOjEwMDAwLCJvZiI6InNwZW5kIiwic2NhbGUiOjIsInVuaXQiOiJVU0QifX0seyJleHAiOjE3OTA3NTU2OTF9XSwiaWF0IjoxNzkwNzI2ODkxLCJpc3MiOiJlZDI1NTE5OlJFTDRiOHdrVmpJNjRjZXJocExodlBoaXFnQnE2Y3BBOG54TU5XbnVuMk0iLCJub25jZSI6ImZUcXJaTVJsenhHT3h6bDYiLCJzdWIiOiJlZDI1NTE5OmhOSTg2ZEt4LVVWTDdmYVM3d09PM25CLWswX01rWHIyRlFQSkZ3a0RsUjQifSwicyI6ImZXLVNmOWdfZ3hySjc5cEc0VnpQY0FVTVkxYk5oZExLTFdiWkdfQnJDbVNHOExNVWEyUWJhUGRRRjlWNndOUVYzZlZKTlRNZHNxYkVvT2ZxWVE0LUR3In1d"
  },
  "slip": {
    "id": "p_wnv-4Z3H",
    "service": "shop.example",
    "summary": "4 meals for 2026-10-01 — 53.95 USD",
    "effects": [
      "+ create order/o1001 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)",
      "+ create charge — 53.95 USD to card ••4242"
    ],
    "uses": "spend 53.95 USD",
    "risk": "low",
    "undo": "within 2h",
    "hash": "S5PYsrlo-mjbUTpP8_MedyFQ4xQJR4aLJG6iZPfsLMM",
    "reason": "spend over the per-commit limit of 40.00 USD; your principal must approve this exact proposal",
    "expires": 1790727540
  },
  "receipt": {
    "id": "r_BXZGdAAm",
    "until": 1790734091,
    "undoUntil": "2026-09-30 02:08 UTC",
    "result": [
      "order: o1001",
      "status: placed"
    ]
  },
  "undone": {
    "id": "r_i81ZaT-Q",
    "undoes": "r_BXZGdAAm"
  },
  "lens": {
    "proposals": "2 proposals — risk: low · undo: 2h · expires: 2026-09-30T00:19Z:\n[p_wnv-4Z3H] 4 meals for 2026-10-01 — 53.95 USD\n  + create order/o1001 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)\n  + create charge — 53.95 USD to card ••4242\n  uses: spend 53.95 USD\n  data:\n    subtotal: 47.96\n    delivery: 5.99\n[p_ITLYXxPR] 4 meals for 2026-10-01 (express, by noon) — 62.94 USD\n  + create order/o1002 — 2× Tofu Pad Thai (light), 2× Chickpea Shawarma (light)\n  + create charge — 62.94 USD to card ••4242\n  uses: spend 62.94 USD\n  data:\n    subtotal: 47.96\n    delivery: 5.99\n    express: 8.99",
    "consent": "✗ consent_required: spend over the per-commit limit of 40.00 USD; your principal must approve this exact proposal\n  consent: principal must approve S5PYsrlo-mjbUTpP8_MedyFQ4xQJR4aLJG6iZPfsLMM (4 meals for 2026-10-01 — 53.95 USD)",
    "receipt": "✓ 4 meals for 2026-10-01 — 53.95 USD (receipt r_BXZGdAAm) · undo until 2026-09-30T02:08:11Z\n  result:\n    order: o1001\n    status: placed",
    "undo": "↶ undid r_BXZGdAAm: 4 meals for 2026-10-01 — 53.95 USD (receipt r_i81ZaT-Q)"
  }
};
